### ISSUE TITLE
Piece in lower hand (the three card section) doesn't "move"

### ISSUE THREAD

**Issue by TheCoolBoss** [olsson22/PalaceAlphaToTestAround#2]
Bug report by Stephen Nguyen
When one piece in the three card hand area was played, it didn't move into the pile and stayed where it was, though the move still registered.  This occurred with at least one of the black colored queens.

**Comment by argiesemann** [comment]
We fixed this problem. The program previously only added a card to another data structure with out changing its Location instance variable.
