### ISSUE TITLE
Portrait vs. Landscape GUI

### ISSUE THREAD

**Issue by mrangutano** [olsson22/PalaceAlphaToTestAround#3]
The game works well! However, while the game allows the player to see more in landscape mode, while the tablet is vertical, it restricts the sight of the player’s cards. 

I believe it would be more helpful for the player if cards were aligned more efficiently while tablet is vertical.

**Comment by olsson22** [comment]
Resolved by changing the AndroidManifest.xml file and hardcoding the orientation to landscape
